Combine all builds into one file, and enable skipping of non code files
TheOpenSpaceProgram/osp-magnum pull request #159
Opened 2021-12-17 12:09 UTC by EhWhoAmI

This PR adds a workflow step that checks if the build has been built before, or if the files edited in the current commit are markdown files, and skips if any of these conditions are met.

Closes #150

2021-12-17 17:36 UTC, z-adams approved these changes

2021-12-17 18:57 UTC, jonesmz requested changes
I'm a big fan of skipping the build if none of the cpp files have changed, but could i ask you to preserve the one file per platform aspect of how the continuous integration is setup? I think that's an important separation.

2021-12-17 21:51 UTC, jonesmz commented on .github/workflows/linux.yml
> +  skip-duplicates:
You shouldn't need to have this be its own job.

I'd prefer just adding the step to the existing job(s) before the checkout step.

Is that possible?

2021-12-17 21:52 UTC, jonesmz commented
Can you also make the analyzers skip? 

There are two jobs in the analyzers file. You'll have to add the check to both jobs.

2021-12-18 00:10 UTC, Capital-Asterisk approved these changes

2021-12-18 00:12 UTC, jonesmz commented
Isn't there a way to abort the whole job right away if the skip checker says to skip?

My reason for not wanting to do a second "job" per platform is because the startup cost of github launching another runner can take a long time.

But if the only way to add this without adding a whole new job is to add if checks to every step, then I'd rather pay the cost of doing a new job per platform.

Could you let me know what the capabilities are?

2021-12-18 00:23 UTC, jonesmz commented on .github/workflows/analyzers.yml
> +        wget https://raw.githubusercontent.com/llvm/llvm-project/llvmorg-11.0.1/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
Looks like you're out if date with master. These lines shouldn't be added back.

2021-12-18 00:24 UTC, EhWhoAmI commented
I don't think it's possible to exit a workflow prematurely, so the current method would have to do.

2021-12-19 08:50 UTC, EhWhoAmI commented
Is this ready for merging?

2022-01-15 01:38 UTC, jonesmz commented
Had git merge problems. Merged via https://github.com/TheOpenSpaceProgram/osp-magnum/pull/167

2022-01-15 01:38 UTC, closed without merging