Simplify build and other build improvements for MSVC
TheOpenSpaceProgram/osp-magnum pull request #44
Opened 2021-01-09 09:27 UTC by EhWhoAmI

MSVC creates different directories for Debug and release builds, and it does not copy all the necessary DLLs to the same directory. 

This reduces the need to copy files manually after each build.

2021-01-10 00:29 UTC, EhWhoAmI commented
I'm gonna skip adding extra command line arguments because I have no idea how to do that.

2021-01-13 18:37 UTC, jonesmz approved these changes
As I said on discord, aside from considering the need to make these changes to be really odd, i don't see anything immediately obviously wrong, so I won't object to this being merged.

@z-adams or @Capital-Asterisk I'll leave it to one of you to merge this.

2021-01-13 20:19 UTC, z-adams requested changes
I'd like to tweak this stuff so don't merge it yet please, I just haven't had time on my desktop to test it.

2021-01-13 23:50 UTC, Capital-Asterisk commented
I have never built on windows before, but I have a branch that sets up the CI to uploads binaries when finished, this might be interesting:

https://github.com/Capital-Asterisk/osp-magnum/tree/release-artifact

I had to manually merge together `build/bin/Release/*` and `build/Release/lib`, and add `build/bin/OSPData` to get it working (on wine). I'm assuming this change will make this unnecessary, which is great for distribution.

2021-01-14 00:03 UTC, EhWhoAmI commented
Yes, it should reduce the need to manually merge the folders together, which is extra annoying when you want a new build.

2021-01-18 02:59 UTC, z-adams approved these changes

2021-01-18 02:59 UTC, merged